### ISSUE TITLE
marker position changed after rotate in high-zoom size use case

### ISSUE THREAD

**Issue by ChongWeiSu** [fnicollet/Leaflet#20]
Hello all,

I'm using the wamp and chrome as my browser to develop an indoor map(higher zoom size).

Already clone the latest Leaflet branch rotate as bellow to implement the rotate function:
https://github.com/Leaflet/Leaflet/tree/rotate

And find that after rotation, the marker's position changed, as bellow:
![output_rsap2y](https://cloud.githubusercontent.com/assets/8374818/24485443/1602cba0-1537-11e7-819c-ffbac851c366.gif)

Is that the javascript's Math precision problem or something else I need to take care about?

Thanks and regards.

**Comment by fnicollet** [comment]
Hello,

It is probably an issue in the rotation code, not taking in account the iconAnchor you provided (in the simplest examples, icons are markers pointing down, so the iconAnchor is at the bottom. In your case, the coordinate of your icon must be the center of the icon.

There is currently a PR done by @sisou so that the markers don't rotate with the map at all:
https://github.com/fnicollet/Leaflet/pull/18
It is still a work in progress but I believe you should check it out, and maybe contribute to the task :)

Fabien

**Comment by ChongWeiSu** [comment]
Hello Fabien,

Seems like #18 patch will resolve this problem.
here's the demonstration with/without #18 patch, and use the default icon to withdraw factor of custom icon.
* without patch:
![origin_default_icon](https://cloud.githubusercontent.com/assets/8374818/24496489/f40ba4fc-156a-11e7-8185-9ea92d9d5454.gif)
* with patch:
![patch_default_icon](https://cloud.githubusercontent.com/assets/8374818/24496531/12ce39e0-156b-11e7-803e-9bc4f1fea788.gif)

Once the patch is merged, I think this issue could be closed, Thanks a lot.

CW

**Comment by fnicollet** [comment]
Thanks for trying out #18 , that's promising :)

Will try it out and merge asap

**Comment by fnicollet** [comment]
The PR has been merged ( #21 ), so give it a go and close the issue if this particular problem is gone

Thanks!
Fabien

**Comment by ChongWeiSu** [comment]
Already pull down the updated code and give it a go, everything works fine.
This issue will be closed.

Thanks for your help.
CW

**Comment by fnicollet** [comment]
Great! Thanks for your feedback
