### ISSUE TITLE
Leaflet with rotate functionality

### ISSUE THREAD

**Issue by johny8228** [fnicollet/Leaflet#31]
Hi,

I would like to ask what is the status of this Leaflet featured version?Is this still being supported.I see it hasn't been merged in a while?Is this project abandoned?

Thanks,
Ionut

**Comment by fnicollet** [comment]
Hello,

Well, I am not working on this project anymore (I don't need that feature anymore), so it is pretty much abandonned, yes. If you merge this branch with leaflet master, it could work or it could not, I have no idea. 

The real solution would be for rotation to be integrated into leaflet's core so that is part of the test suite and maintained as part of the whole project. But at the moment, it is not a priority for leaflet's maintainers and I don't think it will ever be (you need to make quite a lot of changes for rotate to work properly, which could have side effects).

If you really need a map with rotation, I suggest you look at OpenLayers instead, which supports it natively

Fabien
