### ISSUE TITLE
Use the "rotate" branch in the main leaflet repo

### ISSUE THREAD

**Issue by IvanSanchez** [fnicollet/Leaflet#9]
@fnicollet You've got powers to commit to the Leaflet repo. I've rebased this repo based on the 1.0.0 release commit as the `rotate` branch in the main repo, and you're welcome to push commits to it. ;-)

**Comment by itbeyond** [comment]
@fnicollet Are you now using the main leaflet repo. I just downloaded this and built the rotate branch and it seems to be working - I just want to be sure this is the most updated version now. I noticed you did some commits 8 days ago.
Thanks for all your work on this feature.

**Comment by fnicollet** [comment]
@itbeyond Hello, I merged a PR that was done in this repo just when the rotate branch was created on the official repo. So I think I'll need to backport it on the rotate branch too.

I am not sure how to properly work as a Leaflet "experimental" branch as the issues would be "shared" with the main repo, so that might create some noise, while here it stays separated. The workflow is quite new, so I am to try a few options. @IvanSanchez suggested that I created a new repo in the Leaflet organization, so that would basically be just like now, it would just be github/Leaflet/Leaflet-rotate instead of github/fnicollet/Leaflet.

So, not sure yet!

Fabien

**Comment by alexandervlpl** [comment]
@fnicollet Thanks for your amazing work on this! What's the status now? Is this still the best place to get the rotate version and maybe submit some PRs?

**Comment by fnicollet** [comment]
Hello @alexandervlpl and thanks for your message,

I personally don't work on this branch anymore (don't need rotation anymore), so it is pretty much abandonned. A lot of work/refactor has been done on leaflet since, so it is probably not compatible with newer versions anymore.
The official Leaflet issue about rotation is this one:
https://github.com/Leaflet/Leaflet/issues/268
Apparently, someone has tried to merge current master with the rotate work, but I haven't been able to look at it really, so it's at your own risk:
https://github.com/va2ron1/Leaflet

Fabien
